-- Flyway migration script to create the CatProfile table
CREATE TABLE cat_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    breed VARCHAR(255) NOT NULL,
    profile_picture VARCHAR(255) NOT NULL
);